ThaiProgrammer/tech-events-calendar

README.md
Just added Docker in Thai Meetup detail
Very interesting project that welcoming newbies to open source world. Thanks for creating this ;)
(It could be a very long list someday)
=> Add Docker in Thai Meetup detail

.gitignore, grammar.pegjs, ics.js, package-lock.json
ส่ง Parser เข้าประกวดครับ พร้อม ICS Generator สำหรับ #1
=> Parser & ICS Generator per event

generate-json.js, grammar.pegjs
Allow optional columns for #7 and try to fix NaN when parser throws an error.
=> Support optional ⌚️🎟  and summary

.gitignore, package.json, scripts/generate-ics.js
close #14 
- Create script scripts/generate-ics.js
- ignore /public/calendar.ics
- add script node scripts/generate-ics.js to package.json
=> create iCalendar file

README.md
A workshop on google cloud platform instructed by experts from Google itself.
=> Add google cloud onboard 2018.

README.md
An event from [Meetup.com](https://www.meetup.com/ThaiPy-Bangkok-Python-Meetup/events/245135592/)
#1 - "Every language needs its underscore: FP in python" - Alexander Schepanovski
#2 - "TBA" - email the event organizer to become the second speaker
> Monthly meetup for those using python, learning python of just py-curious. Python is one of more popular programming languages in the word and rising further, being used in fields such as web, science, big data, dev-ops and digital entertainment. We to have talks from beginners to advanceก and provide a friendly atmosphere to meet and network with your fellow pythonistas.
=> Add Functional Programming in python by ThaiPy.

README.md
- ThaiPy: 2nd slot now has panel discussion
- Django Girls will be organized on March 10
=> ThaiPy January update + Django Girls

public/_headers, public/index.html
For easy navigation and editing of content
=> Add event index to the homepage

.circleci/config.yml, README.md, lib/grammar.pegjs, package.json, scripts/generate-ci-comment.js, scripts/generate-json.js, scripts/post-ci-comment.js, yarn.lock
(Place details will have inline markdown embedded in JSON)
=> Add Google Maps place links to README.md

package.json, scripts/generate-json.js, yarn.lock
To make diffs displayed by bot smaller
=> Diffy-format JSON for smaller diffs

README.md
=> Add 7 Peaks Tech Events Bangkok: Let's Build a Decentralised Blockchain App on Ethereum

public/index.html
As event name can get long at times.
=> Allow text wrapping in event name

public/go/index.html, public/index.html
=> Permalink (Redirector service)

scripts/generate-ics.js
#56  Changing the url to the updated website
=> Changing the url to the updated website

data/2018-02/asia-pacific-ethereum-meetup.md
Not sure if the event accepts walk-ins, but at least it would be nice to keep as a reference?
Thanks all!
=> Add Asia-Pacific Ethereum Community Meetup

.circleci/config.yml, lib/__snapshots__/parseMarkdown.test.js.snap, package.json
I created 2 command
1.  we can run `yarn snapshot` to update snapshot test
2. we can run `yarn test` to run test
but I'm not sure, we should update snapshot on CI or not.
If you want to I can update it.
---
Closes #58
=> Run Jest on CI

.circleci/config.yml, lib/parseMarkdown.js, lib/parseMarkdown.test.js, package.json, scripts/generate-ics.js, scripts/generate-json.js, scripts/generate-svg.js, website/build/webpack.base.conf.js, website/build/webpack.dev.conf.js, website/build/webpack.prod.conf.js, website/config/index.js, website/package.json, website/src/main.js, website/src/store.js, yarn.lock
I've completed the tasks as instructed.
Close #57
=> Run `standard` on CI

website/src/components/Event.vue, website/src/components/EventInfo.vue, website/src/components/Markdown.vue
So I gave it a shot and added the Markdown component and use it in EventInfo and Event components as instructed.
However, the page now renders a little bit different than before because Markdown added `<p>` tags to the rendered content and I don't wanna touch the CSS 😑
Close #53
=> Add markdown component

data/2018-02/asia-pacific-ethereum-meetup.md, lib/__snapshots__/parseMarkdown.test.js.snap, lib/parseMarkdown.js, lib/parseMarkdown.test.js, website/src/components/EventInfo.vue
=> Add an event's resources and community resources

scripts/generate-json.js
=> Use fs to create directory instead of child_process

scripts/generate-json.js, scripts/generate-svg.js
=> Use mkdirp to support building on Windows

package.json
=> The value of "private" key should be boolean

website/config/index.js, website/index.html, website/static/manifest.json
slove #89 but not enough information
**Need**
* icon
* name
* short name
=> add manifest.json for pwa

website/src/components/ListPage.vue
=> Past events sorting order #99

website/src/components/HomePage.vue
Testing out this PDD thing
http://www.0pdd.com/
=> Add todo comment about calendar link

data/2018-06/angular.md, data/2018-06/ruby-tuesday.md, data/2018-06/tencent.md, data/2018-07/facebook-build-day.md, data/2018-07/sa.md
=> Even more events

data/2018-01/bkk-web-101-angular.md, data/2018-01/insurtech-ignite-workshop.md, data/2018-02/asia-pacific-ethereum-meetup.md, data/2018-07/bangkok-ux.md, data/2018-07/nginx.md, data/2018-09/devops-bkk.md, lib/__snapshots__/parseMarkdown.test.js.snap, lib/parseMarkdown.js, website/package.json, website/src/components/DataEditorPage.vue, website/src/components/DataGeneratorPage.vue, website/src/components/EventInfo.vue, website/src/main.js, website/src/router.js, website/src/store.js, yarn.lock
- Renamed generator to editor.
- Data assistant provides suggestions based on inputted information.
- More strict validation rules.
- Support for TBD locations (in exceptional cases).
=> Improvements to the event editor

data/2018-10/vimpro.md, lib/__snapshots__/parseMarkdown.test.js.snap, lib/parseMarkdown.js, lib/parseMarkdown.test.js
Based on feature request https://github.com/ThaiProgrammer/tech-events-calendar/issues/154, this PR adds that feature.
=> Add google map shortened url support

lib/__snapshots__/parseMarkdown.test.js.snap, lib/parseMarkdown.js, lib/parseMarkdown.test.js
This PR adds Co-create Camp support to category.
=> Add Co-creation Camp support

data/2018-12/code-in-the-dark-2-cnx-2018.md
#181  กิจกรรม อยู่ในระหว่างการเตรียมงานอยู่ครับ https://paper.dropbox.com/doc/Code-in-the-Dark-Thailand-2-CNX-2018-Event-planning-u0TOnNBfpBRzTLSssWKAG
ไฟล์ .md ไม่สามารถใช้ https://calendar.thaiprogrammer.org/editor ตรวจสอบได้ครับ
=> TBD Code in the Dark Thailand CNX 2018

data/2018-10/angular-meetup.md
Angular Meetup at Learn Hub+ Co Learning Space
=> Angular Meetup Oct 2018

scripts/generate-svg.js, website/src/components/HomePage.vue
=> Update calendar to 2019

data/2019-02/wordcamp-bangkok-2019.md
I'll wait for event organizer to add more detail about event
=> WordCamp Bangkok 2019
